services:
  app:
    container_name: app
    build: .
    ports:
      - "2223:22"
    environment:
      - MODEL=${MODEL}
      - BASE_URL=${BASE_URL}
      - API_KEY=${API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      honeypot-net:
        ipv4_address: 172.18.0.20
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs

  attacker-server:
    container_name: attacker-server
    hostname: attacker
    ports:
      - "2221:2221"
    expose:
      - "8080"
      - "15300"
    build: attacker-server/
    networks:
      honeypot-net:
        ipv4_address: 172.18.0.21

networks:
  honeypot-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
