services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    ports:
      - "2222:2222"
    restart: unless-stopped
    networks:
      cowrie-net:
        ipv4_address: 172.18.0.4

  debian-sandbox:
    container_name: debian-sandbox
    hostname: svr04
    ports:
      - "2220:2220"
    build:
      context: .
      dockerfile: debian-sandbox.Dockerfile
    networks:
      cowrie-net:
        ipv4_address: 172.18.0.20
    restart: unless-stopped

  attacker-server:
    container_name: attacker-server
    hostname: attacker-server 
    ports:
      - "2221:2221"
      - "8080:8080"
      - "15300:15300"
    build:
      context: .
      dockerfile: attacker-server.Dockerfile
    networks:
      cowrie-net:
        ipv4_address: 172.18.0.21
    restart: unless-stopped

networks:
  cowrie-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
