from utils import USER, motd

filesystem = {
    "/": {
        "type": "dir",
        "permissions": "drwxr-xr-x",
        "owner": "root",
        "group": "root",
        "modified": "2025-01-15",
        "content": {
            "bin": {
                "type": "symlink",
                "target": "/usr/bin",
                "permissions": "lrwxrwxrwx",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
            },
            "sbin": {
                "type": "symlink",
                "target": "/usr/sbin",
                "permissions": "lrwxrwxrwx",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
            },
            "boot": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-06-20",
                "size": "4096",
                "content": {},
            },
            "dev": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {
                    "null": {
                        "type": "char_device",
                        "permissions": "crw-rw-rw-",
                        "owner": "root",
                        "group": "root",
                        "modified": "2025-01-15",
                        "size": "0",
                    },
                    "zero": {
                        "type": "char_device",
                        "permissions": "crw-rw-rw-",
                        "owner": "root",
                        "group": "root",
                        "modified": "2025-01-15",
                        "size": "0",
                    },
                    "tty": {
                        "type": "char_device",
                        "permissions": "crw-rw-rw-",
                        "owner": "root",
                        "group": "root",
                        "modified": "2025-01-15",
                        "size": "0",
                    },
                },
            },
            "etc": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-04-10",
                "size": "4096",
                "content": {
                    "motd": {
                        "type": "file",
                        "permissions": "-rw-r--r--",
                        "owner": "root",
                        "group": "root",
                        "modified": "2025-03-22",
                        "size": "2KB",
                        "content": motd(),
                    },
                    "passwd": {
                        "type": "file",
                        "permissions": "-rw-r--r--",
                        "owner": "root",
                        "group": "root",
                        "modified": "2025-03-22",
                        "size": "2KB",
                    },
                    "hosts": {
                        "type": "file",
                        "permissions": "-rw-r--r--",
                        "owner": "root",
                        "group": "root",
                        "modified": "2025-01-15",
                        "size": "1KB",
                    },
                    "ssh": {
                        "type": "dir",
                        "permissions": "drwx------",
                        "owner": "root",
                        "group": "root",
                        "modified": "2025-02-01",
                        "size": "4096",
                        "content": {
                            "sshd_config": {
                                "type": "file",
                                "permissions": "-rw-------",
                                "owner": "root",
                                "group": "root",
                                "modified": "2025-02-01",
                                "size": "3KB",
                            }
                        },
                    },
                },
            },
            "home": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {
                    USER: {
                        "type": "dir",
                        "permissions": "drwxr-xr-x",
                        "owner": "user",
                        "group": "user",
                        "modified": "2025-04-05",
                        "size": "4096",
                        "content": {},
                    }
                },
            },
            "lib": {
                "type": "symlink",
                "target": "/usr/lib",
                "permissions": "lrwxrwxrwx",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
            },
            "lib64": {
                "type": "symlink",
                "target": "/usr/lib64",
                "permissions": "lrwxrwxrwx",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
            },
            "media": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {},
            },
            "mnt": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {},
            },
            "opt": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {},
            },
            "proc": {
                "type": "dir",
                "permissions": "dr-xr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {},
            },
            "root": {
                "type": "dir",
                "permissions": "drwx------",
                "owner": "root",
                "group": "root",
                "modified": "2025-04-18",
                "size": "4096",
                "content": {},
            },
            "run": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-04-21",
                "size": "4096",
                "content": {
                    "utmp": {
                        "type": "file",
                        "permissions": "-rw-rw-r--",
                        "owner": "root",
                        "group": "utmp",
                        "modified": "2025-04-21",
                        "size": "1KB",
                    }
                },
            },
            "srv": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {},
            },
            "sys": {
                "type": "dir",
                "permissions": "dr-xr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {},
            },
            "tmp": {
                "type": "dir",
                "permissions": "drwxrwxrwt",
                "owner": "root",
                "group": "root",
                "modified": "2025-04-21",
                "size": "4096",
                "content": {},
            },
            "usr": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {},
            },
            "var": {
                "type": "dir",
                "permissions": "drwxr-xr-x",
                "owner": "root",
                "group": "root",
                "modified": "2025-01-15",
                "size": "4096",
                "content": {},
            },
        },
    }
}

if __name__ == "__main__":
    import pickle

    with open("data/filesystem.pkl", "wb") as pklw:
        pickle.dump(filesystem, pklw)
